services:
  postgres:
    image: postgres:latest
    container_name: postgres_database
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - pg_data_container:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  backend:
    depends_on:
      - postgres
    build: ./backend
    container_name: vangers
    restart: always
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    environment:
      - PORT=${EXTERNAL_PORT}
      - USERNAME=${PG_USER}
      - PASSWORD=${PG_PASSWORD}
      - PORT_DB=${PG_PORT}
      - DATABASE=${PG_DATABASE}
    stdin_open: true
    tty: true
volumes:
  pg_data_container: